# Generated by Django 5.2.12 on 2026-03-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_seed_material_types'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_subjects',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='materials.subject', verbose_name='Oblíbené předměty'),
        ),
    ]
