# Generated by Django 5.2.12 on 2026-03-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_digest_enabled',
            field=models.BooleanField(default=False, help_text='Dostávat týdenní shrnutí nových materiálů emailem.', verbose_name='Týdenní email přehled'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_on_comment',
            field=models.BooleanField(default=True, help_text='Upozornit, když někdo okomentuje váš materiál.', verbose_name='Notifikace při komentáři'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_on_material',
            field=models.BooleanField(default=True, help_text='Upozornit, když je přidán materiál ve vašich oblíbených předmětech.', verbose_name='Notifikace nových materiálů'),
        ),
        migrations.AddField(
            model_name='user',
            name='search_tracking_opt_out',
            field=models.BooleanField(default=False, help_text='Vaše vyhledávání nebude zaznamenáváno do statistik.', verbose_name='Nezaznamenávat mé hledání'),
        ),
    ]
