# Generated by Django 5.2.12 on 2026-03-11 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Vytvoření'), ('update', 'Úprava'), ('delete', 'Smazání'), ('vip_grant', 'Udělení VIP'), ('vip_revoke', 'Odebrání VIP'), ('upload', 'Nahrání souboru')], db_index=True, max_length=20, verbose_name='Akce')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID objektu')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Čas')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP adresa')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Typ objektu')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Uživatel')),
            ],
            options={
                'verbose_name': 'Záznam auditu',
                'verbose_name_plural': 'Záznamy auditu',
                'ordering': ['-timestamp'],
            },
        ),
    ]
