# Generated by Django 5.2.12 on 2026-03-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='default_from_email',
            field=models.EmailField(blank=True, default='', help_text='Např. edubase@skola.cz', max_length=254, verbose_name='Odesílatel (From)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='email_notifications_enabled',
            field=models.BooleanField(default=False, help_text='Odesílat emaily učitelům při nahrání nového materiálu.', verbose_name='Emailové notifikace zapnuty'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='smtp_host',
            field=models.CharField(blank=True, default='', help_text='Např. smtp.gmail.com', max_length=200, verbose_name='SMTP server'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='smtp_password',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='SMTP heslo'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='smtp_port',
            field=models.PositiveSmallIntegerField(default=587, verbose_name='SMTP port'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, verbose_name='Použít TLS'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='smtp_username',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='SMTP uživatel'),
        ),
    ]
