# Generated by Django 5.2.12 on 2026-03-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteconfig_email_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='level',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Varování'), ('error', 'Chyba')], db_index=True, default='info', max_length=10, verbose_name='Úroveň'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Vytvoření'), ('update', 'Úprava'), ('delete', 'Smazání'), ('vip_grant', 'Udělení VIP'), ('vip_revoke', 'Odebrání VIP'), ('upload', 'Nahrání souboru'), ('download', 'Stažení'), ('login', 'Přihlášení'), ('logout', 'Odhlášení'), ('register', 'Registrace'), ('comment_add', 'Přidání komentáře'), ('comment_delete', 'Smazání komentáře')], db_index=True, max_length=20, verbose_name='Akce'),
        ),
    ]
