# Generated by Django 5.2.12 on 2026-03-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='ai_backend',
            field=models.CharField(choices=[('none', 'Vypnuto – pouze Tesseract'), ('google', 'Google Gemini Flash (doporučeno)'), ('anthropic', 'Anthropic Claude Haiku'), ('ollama', 'Ollama – lokálně na serveru (zdarma)')], default='none', help_text='Vyberte poskytovatele AI pro Vision OCR a budoucí funkce (shrnutí, testy).', max_length=20, verbose_name='AI backend'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='anthropic_api_key',
            field=models.CharField(blank=True, default='', help_text='Prepaid kredit, bez předplatného. ~0.11 Kč/obrázek.', max_length=200, verbose_name='Anthropic API klíč'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='google_ai_api_key',
            field=models.CharField(blank=True, default='', help_text='Získejte zdarma na aistudio.google.com – free tier: 1 500 req/den.', max_length=200, verbose_name='Google AI API klíč'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='ocr_lang',
            field=models.CharField(default='ces+eng', help_text='Jazykové balíčky pro Tesseract, např. ces+eng nebo ces.', max_length=50, verbose_name='Tesseract jazyk'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='ocr_pdf_dpi',
            field=models.PositiveSmallIntegerField(default=300, help_text='Rozlišení pro převod PDF stránek na obrázky před OCR. Doporučeno: 300.', verbose_name='PDF OCR – DPI'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='ollama_base_url',
            field=models.CharField(blank=True, default='http://ollama:11434', help_text='URL lokálního Ollama serveru, např. http://ollama:11434', max_length=200, verbose_name='Ollama URL'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='ollama_text_model',
            field=models.CharField(blank=True, default='llama3.1', help_text='Pro shrnutí a generování testů, např. llama3.1 nebo gemma3.', max_length=100, verbose_name='Ollama Text model'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='ollama_vision_model',
            field=models.CharField(blank=True, default='llama3.2-vision', help_text='Doporučeno: llama3.2-vision (11B) nebo llava:7b pro slabší hardware.', max_length=100, verbose_name='Ollama Vision model'),
        ),
    ]
