# Generated by Django 5.2.12 on 2026-03-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_aicalllog_new_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='google_ai_model',
            field=models.CharField(blank=True, default='gemini-1.5-flash', help_text='Doporučeno: gemini-1.5-flash (free tier). Alternativy: gemini-1.5-pro, gemini-2.0-flash-lite.', max_length=100, verbose_name='Google AI model'),
        ),
    ]
