# Generated by Django 5.2.12 on 2026-03-11 22:13

import django.db.models.deletion
import materials.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Název')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Pořadí')),
            ],
            options={
                'verbose_name': 'Typ materiálu',
                'verbose_name_plural': 'Typy materiálů',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Název')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_school_years', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil')),
            ],
            options={
                'verbose_name': 'Ročník',
                'verbose_name_plural': 'Ročníky',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Název')),
                ('slug', models.SlugField(max_length=220, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='materials.schoolyear', verbose_name='Ročník')),
                ('teachers', models.ManyToManyField(blank=True, limit_choices_to={'role': 'teacher'}, related_name='taught_subjects', to=settings.AUTH_USER_MODEL, verbose_name='Učitelé')),
            ],
            options={
                'verbose_name': 'Předmět',
                'verbose_name_plural': 'Předměty',
                'ordering': ['school_year', 'name'],
                'unique_together': {('school_year', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Název')),
                ('file', models.FileField(upload_to=materials.models.material_upload_path, verbose_name='Soubor')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Nahráno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Naposledy upraveno')),
                ('extracted_text', models.TextField(blank=True, default='', help_text='Automaticky vyplněno při nahrání. Slouží pro AI generování testů (V5.0).', verbose_name='Extrahovaný text')),
                ('ocr_processed', models.BooleanField(default=False, verbose_name='OCR zpracováno')),
                ('is_published', models.BooleanField(default=True, verbose_name='Zveřejněno')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='materials.materialtype', verbose_name='Typ')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='materials.subject', verbose_name='Předmět')),
            ],
            options={
                'verbose_name': 'Materiál',
                'verbose_name_plural': 'Materiály',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubjectVIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Uděleno')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vip_grants_given', to=settings.AUTH_USER_MODEL, verbose_name='Udělil')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_users', to='materials.subject', verbose_name='Předmět')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_subjects', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'VIP oprávnění',
                'verbose_name_plural': 'VIP oprávnění',
                'unique_together': {('user', 'subject')},
            },
        ),
    ]
