# Generated by Django 5.2.12 on 2026-03-12 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_seed_material_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Počet stažení'),
        ),
        migrations.AddField(
            model_name='material',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='materials.material', verbose_name='Původní materiál'),
        ),
        migrations.AddField(
            model_name='material',
            name='version',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Verze'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Čas')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Viditelný')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='materials.material', verbose_name='Materiál')),
            ],
            options={
                'verbose_name': 'Komentář',
                'verbose_name_plural': 'Komentáře',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='materials.material', verbose_name='Materiál')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_materials', to=settings.AUTH_USER_MODEL, verbose_name='Uživatel')),
            ],
            options={
                'verbose_name': 'Líbí se mi',
                'verbose_name_plural': 'Líbí se mi',
                'unique_together': {('material', 'user')},
            },
        ),
    ]
