# Generated by Django 5.2.12 on 2026-03-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_download_counter_comments_likes_versioning'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Název')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Štítek',
                'verbose_name_plural': 'Štítky',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='materials', to='materials.tag', verbose_name='Štítky'),
        ),
    ]
