# Generated by Django 5.2.12 on 2026-03-12 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_tag_material_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=300, verbose_name='Dotaz')),
                ('results_count', models.PositiveSmallIntegerField(default=0, verbose_name='Počet výsledků')),
                ('year_filter', models.CharField(blank=True, default='', max_length=120, verbose_name='Filtr ročníku')),
                ('subject_filter', models.CharField(blank=True, default='', max_length=220, verbose_name='Filtr předmětu')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Čas')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to=settings.AUTH_USER_MODEL, verbose_name='Uživatel')),
            ],
            options={
                'verbose_name': 'Log vyhledávání',
                'verbose_name_plural': 'Logy vyhledávání',
                'ordering': ['-timestamp'],
            },
        ),
    ]
