# Generated by Django 5.2.12 on 2026-03-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_icons_external_url_classroom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectyear',
            options={'ordering': ['school_year', 'subject__name'], 'verbose_name': 'Předmět v ročníku', 'verbose_name_plural': 'Předměty v ročnících'},
        ),
        migrations.AlterField(
            model_name='material',
            name='external_url',
            field=models.URLField(blank=True, default='', help_text='Odkaz na Google Docs, Slides, Sheets apod. (místo souboru)', max_length=1000, verbose_name='Externí odkaz'),
        ),
        migrations.AlterField(
            model_name='material',
            name='icon',
            field=models.CharField(default='📄', help_text='Emoji ikona materiálu', max_length=20, verbose_name='Ikona'),
        ),
        migrations.AlterField(
            model_name='subjectyear',
            name='classroom_link',
            field=models.URLField(blank=True, default='', help_text='Volitelný odkaz na třídu v Google Classroom (vyplní učitel)', max_length=500, verbose_name='Google Classroom odkaz'),
        ),
    ]
